version: "3.8"
services:
  nginx:
    image: 635728122877.dkr.ecr.ap-southeast-1.amazonaws.com/cz2006-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: 635728122877.dkr.ecr.ap-southeast-1.amazonaws.com/cz2006-api
    build: api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  client:
    image: 635728122877.dkr.ecr.ap-southeast-1.amazonaws.com/cz2006-client
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules: